on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dockerregistry1232.azurecr.io
        username: ${{ secrets.acr_dockerregistry1232_username }}
        password: ${{ secrets.acr_dockerregistry1232_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dockerregistry1232.azurecr.io/clusterkube:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push dockerregistry1232.azurecr.io/clusterkube:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_clusterkube_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep clusterkubeac4a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace clusterkubeac4a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: clusterkubeac4a
        container-registry-url: dockerregistry1232.azurecr.io
        container-registry-username: ${{ secrets.acr_dockerregistry1232_username }}
        container-registry-password: ${{ secrets.acr_dockerregistry1232_password }}
        secret-name: clusterkubedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: clusterkubeac4a
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          dockerregistry1232.azurecr.io/clusterkube:${{ github.sha }}
        imagepullsecrets: |
          clusterkubedockerauth
